---
title: "Bourgeois-Pichat"
author: "Göran Broström"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Data

```{r readdata}
infant <- readRDS("Rdata/infant.rds")
infant <- infant[infant$sex != 0, ]
infant$sex <- factor(infant$sex, labels = c("boy", "girl"))
weq <- with(infant, ((exit < 364.5) & (event == 0)) |
                (bdupd == 1))
inf0 <- infant[!weq, ]
g <- function(x) (log(1 + x)) ^ 3
g0 <- function(x) g(x) * 365 / g(365)
```

# BP with inf0

```{r}
library(eha)
x <- with(inf0, Surv(enter, exit, event))
rs <- risksets(x, members = FALSE)
```

## Without transformation

```{r rawm, fig.cap = "Bourgeois-Pichat curve, no transformation."}
n <- NROW(inf0)
par(las = 1)
with(rs, plot(risktimes, cumsum(n.events) / n, type = "l", xlab = "Days", ylab = "CDF"))
```


## With transformation

```{r gtrans, fig.cap = "Bougeois-Pichat with log-cube transformation."}
n <- NROW(inf0)
with(rs, plot(risktimes, cumsum(n.events) / n, type = "l", axes = FALSE,
     xlab = "Age (days)", ylab = "CDF", col = "blue"))
with(rs, lines(g0(risktimes), cumsum(n.events) / n, col = "red"))
att <- c(0, 30, 60, 120, 240, 365)
axis(1, at = att, col = "blue", labels = att)
axis(3, at = g0(att), col = "red", labels = att)
axis(2, las = 1)
box()
abline(h = 0)
abline(v = g0(30), lty = 3, col = "red")
abline(v = 30, lty = 3)
abline(h = 0.0255, lty = 3, col = "darkgreen")
abline(v = 0)
```

## Postneonatal mortality

We create a New data set that contains postneonatal data on a transformed 
time scale, first the *age.window*,  then $g$ transform, then set start of postneonatal period to zero.

```{r postneo}
pneo <- age.window(infant, c(31, 365))
gpneo <- pneo
gpneo$exit <- g(gpneo$exit)
gpneo$enter <- g(pneo$enter)
```

